# ./docker-compose.yaml
version: '3.2'

services:
  urlsh:
    image: golang:1.14
    working_dir: /go/src/app
    command: sh -c 'sleep 5 && go run main.go'
    ports:
      - ${APP_PORT:-1000}:${APP_PORT:-1000}
    volumes:
      - .:/go/src/app:delegated
    env_file:
      - .env
    environment:
      - APP_DB_DSN=host=urlshdb port=5432 user=${POSTGRES_USER:-postgres} password=${POSTGRES_PASSWORD:-postgres} dbname=urlsh sslmode=disable
    depends_on:
      - urlshdb

  urlshdb:
    image: postgres:12.4
    ports:
      - 2000:5432
    volumes:
      - dbdata:/var/lib/postgresql
      - ./init-test-db.sh:/docker-entrypoint-initdb.d/init-test-db.sh
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=urlsh

volumes:
  dbdata:
