name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    name: test
    steps:
      - uses: actions/checkout@v2
      - name: docker-up
        run: 'cp .env.example .env && docker-compose up -d'
      - name: test
        run: 'sleep 5 && docker-compose exec -T urlsh sh -c "APP_ENV=test go test -cover ./..."'
